const formulesData = [
  {
    id: 1,
    title: "Formule Basique",
    price: "1 500.00 €",
    secondPrice: "394.00 €",
    bg: "basique",
    description: {
      maquette: "✔️",
      personalisation: "✔️",
      contenu: "❌",
      web: "✔️",
      mobile: "✔️",
      hebergement: "1 an offert",
      pages: "1-3",
      remboursement: "✔️",
      reseaux: "❌",
      stratégies: "❌",
      conseils: "❌",
      changement: "❌",
      accompagnement: "❌",
      partenaires: "❌",
    },
  },
  {
    id: 2,
    title: "Formule Plus",
    price: "3 000.00 €",
    secondPrice: "394.00 €",
    bg: "plus",
    description: {
      maquette: "✔️",
      personalisation: "✔️",
      contenu: "❌",
      web: "✔️",
      mobile: "✔️",
      hebergement: "2 ans offert",
      pages: "1-5",
      remboursement: "✔️",
      changement: "1 fois/an",
      stratégies: "❌",
      conseils: "❌",
      reseaux: "❌",
      accompagnement: "✔️",
      partenaires: "✔️",
    },
  },
  {
    id: 3,
    title: "Formule Extra",
    price: "4 500.00 €",
    secondPrice: "394.00 €",
    bg: "extra",
    description: {
      maquette: "✔️",
      personalisation: "✔️",
      contenu: "✔️",
      web: "✔️",
      mobile: "✔️",
      hebergement: "4 ans offert",
      pages: "illimité",
      remboursement: "✔️",
      changement: "1 fois/mois",
      stratégies: "✔️",
      conseils: "✔️",
      reseaux: "✔️",
      accompagnement: "✔️",
      partenaires: "✔️",
    },
  },
];

export default formulesData;
