const formulesData = [
  {
    id: 1,
    title: "Formule Basique",
    price: "600.00 €",
    secondPrice: "157.60 €",
    bg: "",
    description: {
      maquette: "basique",
      personalisation: "basique",
      contenu: "✔️",
      domaine: "✔️",
      web: "✔️",
      mobile: "✔️",
      hebergement: "10€/mois",
      pages: "1-3",
      remboursement: "✔️",
      contact: "❌",
      reseaux: "❌",
    },
  },
  {
    id: 2,
    title: "Formule Plus",
    price: "1500.00 €",
    secondPrice: "394.00 €",

    bg: "",
    description: {
      maquette: "personalisée",
      personalisation: "totale",
      contenu: "✔️",
      domaine: "✔️",
      web: "✔️",
      mobile: "✔️",
      hebergement: "✔️",
      pages: "1-5",
      remboursement: "✔️",
      contact: "✔️",
      reseaux: "✔️",
    },
  },
  {
    id: 3,
    title: "Formule mensuel",
    price: "35€/mois",
    bg: "",
    description: {
      maquette: "personalisée",
      personalisation: "totale",
      web: "✔️",
      mobile: "✔️",
      contenu: "✔️",
      domaine: "✔️",
      hebergement: "✔️",
      pages: "1-3",
      remboursement: "❌",
      contact: "❌",
      reseaux: "❌",
    },
  },
];

export default formulesData;
