const formulesData = [
  {
    id: 1,
    title: "Formule Basique",
    price: "600.00 €",
    secondPrice: "120.00 €",
    bg: "",
    description: {
      maquette: "basique",
      personalisation: "basique",
      contenu: "✔️",
      domaine: "✔️",
      web: "✔️",
      mobile: "✔️",
      hebergement: "❌",
      pages: "1-3",
      remboursement: "✔️",
      contact: "❌",
      reseaux: "❌",
      autre: "10€/mois pour l'hébergement",
    },
  },
  {
    id: 2,
    title: "Formule Plus",
    price: "1500.00 €",
    secondPrice: "300.00 €",

    bg: "",
    description: {
      maquette: "personalisée",
      personalisation: "totale",
      contenu: "✔️",
      domaine: "✔️",
      web: "✔️",
      mobile: "✔️",
      hebergement: "✔️",
      pages: "1-5",
      remboursement: "✔️",
      contact: "✔️",
      reseaux: "✔️",
      autre: "Aucun paiement mensuel",
    },
  },
  {
    id: 3,
    title: "Formule mensuel",
    price: "35€/mois",
    bg: "",
    description: {
      maquette: "personalisée",
      personalisation: "totale",
      web: "✔️",
      mobile: "✔️",
      contenu: "✔️",
      domaine: "✔️",
      hebergement: "✔️",
      pages: "1-3",
      remboursement: "❌",
      contact: "❌",
      reseaux: "❌",
      autre: "Paiement initial de 150.00 €",
    },
  },
];

export default formulesData;
